KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  serviceName="kafkaclient"
  security.protocol=SASL_PLAINTEXT
  sasl.mechanism=PLAIN
  group.id="test"
  bootstrap.servers="localhost:9096"
  username="admin"
  password="admin";
};